<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet href="default.css" type="text/css" ?>

<!DOCTYPE appelsOffre [
	<!ELEMENT appelsOffre (appel+)>

	<!ELEMENT appel (suivi,cahier,client)>

	<!ELEMENT suivi (dateAppel,typeAppel,etatAppel)>
	<!ELEMENT dateAppel (#PCDATA)>
	<!ELEMENT typeAppel (#PCDATA)>
	<!ELEMENT etatAppel (#PCDATA)>

	<!ELEMENT cahier (dateCahier,nomRespCahier,montantCahier)>
	<!ELEMENT dateCahier (#PCDATA)>
	<!ELEMENT nomRespCahier (#PCDATA)>
	<!ELEMENT montantCahier (#PCDATA)>

	<!ELEMENT client (raisonSocialeClient,nomContactClient)>
	<!ELEMENT raisonSocialeClient (#PCDATA)>
	<!ELEMENT nomContactClient (#PCDATA)>
]>

<appelsOffre>
	<appel>
		<suivi>
			<dateAppel>24/01/12</dateAppel>
			<typeAppel>Marché public</typeAppel>
			<etatAppel>Emporté</etatAppel>
		</suivi>
		<cahier>
			<dateCahier>02/02/12</dateCahier>
			<nomRespCahier>Alphonse Lepitre</nomRespCahier>
			<montantCahier>35000</montantCahier>
		</cahier>
		<client>
			<raisonSocialeClient>MRSInfo</raisonSocialeClient>
			<nomContactClient>Mr Duval</nomContactClient>
		</client>
	</appel>

	<appel>
		<suivi>
			<dateAppel>21/02/12</dateAppel>
			<typeAppel>Marché public</typeAppel>
			<etatAppel>En cours</etatAppel>
		</suivi>
		<cahier>
			<dateCahier>04/03/12</dateCahier>
			<nomRespCahier>Mr Grimaud</nomRespCahier>
			<montantCahier>120000</montantCahier>
		</cahier>
		<client>
			<raisonSocialeClient>Région PACA</raisonSocialeClient>
			<nomContactClient>Mr Demetz</nomContactClient>
		</client>
	</appel>

	<appel>
		<suivi>
			<dateAppel>25/04/12</dateAppel>
			<typeAppel>Marché public</typeAppel>
			<etatAppel>En cours</etatAppel>
		</suivi>
		<cahier>
			<dateCahier>10/05/12</dateCahier>
			<nomRespCahier>Mr Grimaud</nomRespCahier>
			<montantCahier>50000</montantCahier>
		</cahier>
		<client>
			<raisonSocialeClient>Région PACA</raisonSocialeClient>
			<nomContactClient>Mr Demetz</nomContactClient>
		</client>
	</appel>
</appelsOffre>